# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    increment_build_number
    build_app
    upload_to_testflight  # Archive, validate and upload the binary to Testflight
  end
  
  lane :release do
    capture_screenshots
    clear_derived_data
    build_app
    upload_to_app_store       # Upload the screenshots and the binary to iTunes
    slack                     # Let your team-mates know the new version is live
  end
  
  lane :test do
    swiftlint(output_file: "swiftlint.result.json", 
      reporter: "json", 
      ignore_exit_status: true)
    scan
  end
end
